Updated to l4re snapshot 18.09

diff --git a/bin/setup.d/04-setup b/bin/setup.d/04-setup
--- a/bin/setup.d/04-setup
+++ b/bin/setup.d/04-setup
@@ -184,7 +184,7 @@ do_config()
     # query cross compiler prefix
     if [ -n "$CONF_DO_ARM" ]; then
       dialog --no-mouse --visit-items \
-	--inputbox "ARM cross compiler prefix (CROSS_COMPILE)" 8 70 "arm-linux-" \
+	--inputbox "ARM cross compiler prefix (CROSS_COMPILE)" 8 70 "arm-linux-gnueabihf-" \
 	2> $tmpfile
       CROSS_COMPILE_ARM=$(cat $tmpfile)
     fi
@@ -375,7 +375,9 @@ switch_to_kconfig_setup_arm()
 
 add_std_qemu_options()
 {
-  echo "QEMU_OPTIONS += -m 256 -serial stdio" >> $1
+  mem=$2
+  [ -z "$mem" ] && mem=256
+  echo "QEMU_OPTIONS += -m $mem -serial stdio" >> $1
   if [ -n "$REMOTE" ]; then
     echo "QEMU_OPTIONS += -vnc :4" >> $1
   fi
@@ -485,16 +487,52 @@ check_tools()
 do_setup()
 {
   echo CONF_DO_ARM64=$CONF_DO_ARM64
-  [ "$CONF_DO_X86_32" ] && fiasco_configs="$fiasco_configs ia32"
-  [ "$CONF_DO_X86_32" -a "$CONF_DO_UX" ] && fiasco_configs="$fiasco_configs ux"
+  [ "$CONF_DO_X86_32" ] && fiasco_configs="$fiasco_configs ia32-1"
+  [ "$CONF_DO_X86_32" -a "$CONF_DO_UX" ] && fiasco_configs="$fiasco_configs ux-1"
   [ "$CONF_DO_ARM64" ] && fiasco_configs="$fiasco_configs arm64-mp-vexpress"
-  [ "$CONF_DO_AMD64" ] && fiasco_configs="$fiasco_configs amd64"
-  [ "$CONF_DO_ARM_RV_ARM9" ] && fiasco_configs="$fiasco_configs arm-mp-rv-pb11mp arm-up-rv-9"
-  [ "$CONF_DO_ARM_RV_CA" ] && fiasco_configs="$fiasco_configs arm-mp-rv-a9-vexpress"
-  [ "$CONF_DO_ARM_OMAP_BB" ] && fiasco_configs="$fiasco_configs arm-beagleboard"
-  [ "$CONF_DO_ARM_OMAP_PANDA" ] && fiasco_configs="$fiasco_configs arm-pandaboard"
-  [ "$CONF_DO_MIPS32R2" ] && fiasco_configs="$fiasco_configs mips32-baikal-mp mips32-malta"
-  [ "$CONF_DO_MIPS64R2" ] && fiasco_configs="$fiasco_configs mips64r2-malta"
+  [ "$CONF_DO_AMD64" ] && fiasco_configs="$fiasco_configs amd64-1"
+  [ "$CONF_DO_ARM_RV_ARM9" ] && fiasco_configs="$fiasco_configs arm-v6-mp-pb arm-rv-1"
+  [ "$CONF_DO_ARM_RV_CA" ] && fiasco_configs="$fiasco_configs arm-a9-mp-vexpress-1"
+  [ "$CONF_DO_ARM_OMAP_BB" ] && fiasco_configs="$fiasco_configs arm-omap3evm"
+  [ "$CONF_DO_ARM_OMAP_PANDA" ] && fiasco_configs="$fiasco_configs arm-omap4-panda"
+  [ "$CONF_DO_MIPS32R2" ] && fiasco_configs="$fiasco_configs mips-baikal-mp mips-malta-mp"
+  [ "$CONF_DO_MIPS32R6" ] && fiasco_configs="$fiasco_configs mips-malta-32r6-mp"
+  [ "$CONF_DO_MIPS64R2" ] && fiasco_configs="$fiasco_configs mips-malta-64r2-mp"
+  [ "$CONF_DO_MIPS64R6" ] && fiasco_configs="$fiasco_configs mips-malta-64r6-mp mips-boston-64r6-mp"
+
+  declare -A fiascodirs
+  fiascodirs[ia32-1]="ia32"
+  fiascodirs[ux-1]="ux"
+  fiascodirs[amd64-1]="amd64"
+  fiascodirs[arm64-mp-vexpress]="arm64-mp-vexpress"
+  fiascodirs[arm-v6-mp-pb]="arm-mp-rv-pb11mp"
+  fiascodirs[arm-rv-1]="arm-up-rv-9"
+  fiascodirs[arm-a9-mp-vexpress-1]="arm-mp-rv-a9-vexpress"
+  fiascodirs[arm-omap3evm]="arm-beagleboard"
+  fiascodirs[arm-omap4-panda]="arm-pandaboard"
+  fiascodirs[mips-malta-mp]="mips32-malta"
+  fiascodirs[mips-baikal-mp]="mips32-baikal-mp"
+  fiascodirs[mips-malta-32r6-mp]="mips-malta-32r6-mp"
+  fiascodirs[mips-malta-64r2-mp]="mips64r2-malta"
+  fiascodirs[mips-boston-64r6-mp]="mips-boston-64r6-mp"
+  fiascodirs[mips-malta-64r6-mp]="mips-malta-64r6-mp"
+
+  declare -A fiascocrosscomp
+  fiascocrosscomp[ia32-1]=$CROSS_COMPILE_X86_32
+  fiascocrosscomp[ux-1]=$CROSS_COMPILE_X86_32
+  fiascocrosscomp[amd64-1]=$CROSS_COMPILE_AMD64
+  fiascocrosscomp[arm64-mp-vexpress]=$CROSS_COMPILE_ARM64
+  fiascocrosscomp[arm-v6-mp-pb]=$CROSS_COMPILE_ARM
+  fiascocrosscomp[arm-rv-1]=$CROSS_COMPILE_ARM
+  fiascocrosscomp[arm-a9-mp-vexpress-1]=$CROSS_COMPILE_ARM
+  fiascocrosscomp[arm-omap3evm]=$CROSS_COMPILE_ARM
+  fiascocrosscomp[arm-omap4-panda]=$CROSS_COMPILE_ARM
+  fiascocrosscomp[mips-malta-mp]=$CROSS_COMPILE_MIPS32R2
+  fiascocrosscomp[mips-baikal-mp]=$CROSS_COMPILE_MIPS32R2
+  fiascocrosscomp[mips-malta-32r6-mp]=$CROSS_COMPILE_MIPS32R6
+  fiascocrosscomp[mips-malta-64r2-mp]=$CROSS_COMPILE_MIPS64R2
+  fiascocrosscomp[mips-boston-64r6-mp]=$CROSS_COMPILE_MIPS64R6
+  fiascocrosscomp[mips-malta-64r6-mp]=$CROSS_COMPILE_MIPS64R6
 
   echo "Creating build directories..."
 
@@ -506,79 +544,32 @@ do_setup()
 
   # Fiasco build dirs
   for b in $fiasco_configs; do
-    echo $b
-    (cd src/kernel/fiasco && make B=../../../obj/fiasco/$b)
+    echo ${fiascodirs[$b]} "->" $b
+    if [ -z "${fiascodirs[$b]}" ]; then
+      echo "Internal error: No directory given for config '$b'"
+      exit 1
+    fi
+    (cd src/kernel/fiasco && make B=../../../obj/fiasco/${fiascodirs[$b]} T=$b)
+    echo CROSS_COMPILE=${fiascocrosscomp[$b]} >> obj/fiasco/${fiascodirs[$b]}/Makeconf.local
   done
 
-  # fiasco build dirs with defaults configs
-  if [ "$CONF_DO_X86_32" ]; then
-    if [ "$CONF_DO_UX" ]; then
-      cp src/kernel/fiasco/src/templates/globalconfig.out.ux-1 \
-         obj/fiasco/ux/globalconfig.out
-      echo CROSS_COMPILE=$CROSS_COMPILE_X86_32 >> obj/fiasco/ux/Makeconf.local
-    fi
-    cp src/kernel/fiasco/src/templates/globalconfig.out.ia32-1 \
-       obj/fiasco/ia32/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_X86_32 >> obj/fiasco/ia32/Makeconf.local
-  fi
-  if [ "$CONF_DO_AMD64" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.amd64-1 \
-       obj/fiasco/amd64/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_AMD64 >> obj/fiasco/amd64/Makeconf.local
-  fi
-  if [ "$CONF_DO_ARM_RV_ARM9" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.arm-v6-mp-pb \
-       obj/fiasco/arm-mp-rv-pb11mp/globalconfig.out
-    cp src/kernel/fiasco/src/templates/globalconfig.out.arm-rv-1 \
-       obj/fiasco/arm-up-rv-9/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/fiasco/arm-mp-rv-pb11mp/Makeconf.local
-    echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/fiasco/arm-up-rv-9/Makeconf.local
-  fi
-  if [ "$CONF_DO_ARM_RV_CA" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.arm-a9-mp-vexpress-1 \
-       obj/fiasco/arm-mp-rv-a9-vexpress/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/fiasco/arm-mp-rv-a9-vexpress/Makeconf.local
-  fi
+  # some config tweaking
   if [ "$CONF_DO_ARM_OMAP_BB" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.arm-omap3evm \
-       obj/fiasco/arm-beagleboard/globalconfig.out
     # beagleboard is nearly omap3evm so we do not have an own config
     perl -n -i -e 'print unless /CONFIG_PF_OMAP3_/' obj/fiasco/arm-beagleboard/globalconfig.out
     echo "# CONFIG_PF_OMAP3_OMAP35XEVM is not set" >> obj/fiasco/arm-beagleboard/globalconfig.out
     echo "# CONFIG_PF_OMAP3_AM33XX is not set" >> obj/fiasco/arm-beagleboard/globalconfig.out
     echo "CONFIG_PF_OMAP3_BEAGLEBOARD=y"    >> obj/fiasco/arm-beagleboard/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/fiasco/arm-beagleboard/Makeconf.local
-  fi
-  if [ "$CONF_DO_ARM_OMAP_PANDA" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.arm-omap4-panda \
-       obj/fiasco/arm-pandaboard/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/fiasco/arm-pandaboard/Makeconf.local
   fi
   if [ "$CONF_DO_MIPS32R2" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.mips-baikal-mp \
-       obj/fiasco/mips32-baikal-mp/globalconfig.out
-    cp src/kernel/fiasco/src/templates/globalconfig.out.mips-malta-mp \
-       obj/fiasco/mips32-malta/globalconfig.out
     echo '# CONFIG_MP is not set' >> obj/fiasco/mips32-malta/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_MIPS32R2 >> obj/fiasco/mips32-baikal-mp/Makeconf.local
-    echo CROSS_COMPILE=$CROSS_COMPILE_MIPS32R2 >> obj/fiasco/mips32-malta/Makeconf.local
-  fi
-  if [ "$CONF_DO_MIPS64R2" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.mips-malta-64r2-mp \
-       obj/fiasco/mips64r2-malta/globalconfig.out
-    echo CROSS_COMPILE=$CROSS_COMPILE_MIPS64R2 >> obj/fiasco/mips64r2-malta/Makeconf.local
-  fi
-
-  if [ "$CONF_DO_ARM64" ]; then
-    cp src/kernel/fiasco/src/templates/globalconfig.out.arm64-mp-vexpress \
-       obj/fiasco/arm64-mp-vexpress/globalconfig.out
-    echo '# ' >> obj/fiasco/arm64-mp-vexpress/Makeconf.local
-    echo CROSS_COMPILE=$CROSS_COMPILE_ARM64 >> obj/fiasco/arm64-mp-vexpress/Makeconf.local
   fi
 
   for b in $fiasco_configs; do
-    make -C obj/fiasco/$b olddefconfig
+    make -j5 -C obj/fiasco/${fiascodirs[$b]} olddefconfig
   done
+
+
 
   # L4Re build dirs with default configs
   [ "$CONF_DO_X86_32" ] \
@@ -588,34 +579,34 @@ do_setup()
     && make -C src/l4 DROPSCONF_DEFCONFIG=mk/defconfig/config.amd64 B=../../obj/l4/amd64
 
   if [ "$CONF_DO_ARM_RV_ARM9" ]; then
-    make -C src/l4 DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-arm9
+    make -C src/l4 CROSS_COMPILE=$CROSS_COMPILE_ARM DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-arm9
     ARM_L4_DIR_FOR_LX_UP=obj/l4/arm-arm9
     echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/l4/arm-arm9/Makeconf.local
   fi
   if [ "$CONF_DO_ARM_RV_CA" ]; then
-    make -C src/l4 DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-ca
+    make -C src/l4 CROSS_COMPILE=$CROSS_COMPILE_ARM DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-ca
     #echo 'RAM_BASE:=0x60000000' > obj/l4/arm-ca/Makeconf.ram_base
     switch_to_kconfig_setup_arm obj/l4/arm-ca/.kconfig \
                                 CONFIG_CPU_ARM_ARMV7A CONFIG_PLATFORM_TYPE_rv_vexpress
-    make -C obj/l4/arm-ca oldconfig
+    make -C obj/l4/arm-ca CROSS_COMPILE=$CROSS_COMPILE_ARM oldconfig
     ARM_L4_DIR_FOR_LX_MP=obj/l4/arm-ca
     echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/l4/arm-ca/Makeconf.local
   fi
   if [ "$CONF_DO_ARM_OMAP_BB" ]; then
-    make -C src/l4 DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-beagleboard
+    make -C src/l4 CROSS_COMPILE=$CROSS_COMPILE_ARM DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-beagleboard
     switch_to_kconfig_setup_arm obj/l4/arm-beagleboard/.kconfig \
                                 CONFIG_CPU_ARM_ARMV7A CONFIG_PLATFORM_TYPE_beagleboard
-    make -C obj/l4/arm-beagleboard oldconfig
+    make -C obj/l4/arm-beagleboard CROSS_COMPILE=$CROSS_COMPILE_ARM oldconfig
     if [ -z "$ARM_L4_DIR_FOR_LX_UP" ]; then
       ARM_L4_DIR_FOR_LX_UP=obj/l4/arm-beagleboard
     fi
     echo CROSS_COMPILE=$CROSS_COMPILE_ARM >> obj/l4/arm-beagleboard/Makeconf.local
   fi
   if [ "$CONF_DO_ARM_OMAP_PANDA" ]; then
-    make -C src/l4 DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-pandaboard
+    make -C src/l4 CROSS_COMPILE=$CROSS_COMPILE_ARM DROPSCONF_DEFCONFIG=mk/defconfig/config.arm-rv B=../../obj/l4/arm-pandaboard
     switch_to_kconfig_setup_arm obj/l4/arm-pandaboard/.kconfig \
                                 CONFIG_CPU_ARM_ARMV7A CONFIG_PLATFORM_TYPE_pandaboard
-    make -C obj/l4/arm-pandaboard oldconfig
+    make -C obj/l4/arm-pandaboard CROSS_COMPILE=$CROSS_COMPILE_ARM oldconfig
     if [ -z "$ARM_L4_DIR_FOR_LX_UP" ]; then
       ARM_L4_DIR_FOR_LX_UP=obj/l4/arm-pandaboard
     fi
@@ -623,7 +614,7 @@ do_setup()
   fi
 
   if [ "$CONF_DO_ARM64" ]; then
-    make -C src/l4 DROPSCONF_DEFCONFIG=mk/defconfig/config.arm64-rv-v8a B=../../obj/l4/arm64
+    make -C src/l4 CROSS_COMPILE=$CROSS_COMPILE_ARM64 DROPSCONF_DEFCONFIG=mk/defconfig/config.arm64-rv-v8a B=../../obj/l4/arm64
   fi
 
   if [ "$CONF_DO_MIPS32R2" ]; then
@@ -655,7 +646,7 @@ do_setup()
   fi
   if [ "$CONF_DO_MIPS64R6" ]; then
     cp src/l4/mk/defconfig/config.mips .tmp1
-    echo CONFIG_PLATFORM_TYPE_malta=y >> .tmp1
+    echo CONFIG_PLATFORM_TYPE_boston=y >> .tmp1
     echo CONFIG_CPU_MIPS_64R6=y >> .tmp1
     make -C src/l4 DROPSCONF_DEFCONFIG=../../.tmp1 \
       CROSS_COMPILE=$CROSS_COMPILE_MIPS64R6 B=../../obj/l4/mips64r6
@@ -687,15 +678,19 @@ do_setup()
     ( cd src/l4linux && make L4ARCH=arm CROSS_COMPILE=$CROSS_COMPILE_ARM O=../../obj/l4linux/arm-up arm_defconfig )
     perl -p -i -e 's@^(CONFIG_L4_OBJ_TREE=").*@$1'"$(cd $ARM_L4_DIR_FOR_LX_UP && pwd)"'"@' \
        obj/l4linux/arm-up/.config
+    perl -p -i -e 's@^(CONFIG_CROSS_COMPILE)=""$@$1="'$CROSS_COMPILE_ARM'"@' \
+       obj/l4linux/arm-up/.config
 
     if [ "$ARM_L4_DIR_FOR_LX_MP" ]; then
       mkdir -p obj/l4linux/arm-mp
       ( cd src/l4linux && make L4ARCH=arm CROSS_COMPILE=$CROSS_COMPILE_ARM O=../../obj/l4linux/arm-mp arm-mp_defconfig )
       perl -p -i -e 's@^(CONFIG_L4_OBJ_TREE=").*@$1'"$(cd $ARM_L4_DIR_FOR_LX_MP && pwd)"'"@' \
 	 obj/l4linux/arm-mp/.config
+      perl -p -i -e 's@^(CONFIG_CROSS_COMPILE)=""$@$1="'$CROSS_COMPILE_ARM'"@' \
+	 obj/l4linux/arm-mp/.config
     fi
 
-    if ! check_eabi_gcc arm-linux-gcc; then
+    if ! check_eabi_gcc ${CROSS_COMPILE_ARM}gcc; then
       echo "WARNING: L4Linux has been disabled due to a detected old OABI compiler"
       echo "WARNING: Please update your compiler to an EABI version"
       add_to_config SKIP_L4LINUX_ARM_BUILD=1
@@ -791,7 +786,7 @@ EOF
   if [ "$CONF_DO_MIPS64R2" ]; then
     mkdir -p obj/l4/mips64r2/conf
     cat<<EOF >> obj/l4/mips64r2/conf/Makeconf.boot
-MODULE_SEARCH_PATH=$(pwd)/obj/fiasco/mips64-malta:$common_paths
+MODULE_SEARCH_PATH=$(pwd)/obj/fiasco/mips-malta-64r2-mp:$common_paths
 QEMU_OPTIONS += -M malta
 EOF
     add_std_qemu_options obj/l4/mips64r2/conf/Makeconf.boot
@@ -801,10 +796,11 @@ EOF
   if [ "$CONF_DO_MIPS64R6" ]; then
     mkdir -p obj/l4/mips64r6/conf
     cat<<EOF >> obj/l4/mips64r6/conf/Makeconf.boot
-MODULE_SEARCH_PATH=$(pwd)/obj/fiasco/mips64-...:$common_paths
-QEMU_OPTIONS += -M malta
+MODULE_SEARCH_PATH=$(pwd)/obj/fiasco/mips-boston-64r6-mp:$common_paths
+QEMU_OPTIONS    += -M boston
+QEMU_KERNEL_TYPE = itb
 EOF
-    add_std_qemu_options obj/l4/mips64r6/conf/Makeconf.boot
+    add_std_qemu_options obj/l4/mips64r6/conf/Makeconf.boot 1024
     add_nonx86_qemu_options obj/l4/mips64r6/conf/Makeconf.boot
   fi
 }
